=== deckeeee/F-11/f-11-2.1.24/testResources/resources/task/tasks_1_0.dtd
<!--
  Automatic printing task definition Version 1.0
  Copyright (C) 2004 Freedom, Inc. All Rights Reserved.

  This program is free software; you can redistribute it and/or
  modify it under the terms of the GNU General Public License
  as published by the Free Software Foundation; either version 2
  of the License, or (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
-->

<!--
  Please take in as follows to an automatic printing task definition file.

  <!DOCTYPE tasks PUBLIC
          "-//Project F-11//DTD F-11 Task Configuration 1.0//JP"
          "http://f-11.sourceforge.jp/dtds/tasks_1_0.dtd">
-->

<!--
  A tasks element is the route element of an automatic printing definition.
-->
<!ELEMENT tasks (schedule*)>

<!--
  A scheduler element defines a scheduler.
  Usually, `org.F11.scada.scheduling.Schedule' is specified.
-->
<!ELEMENT schedule (task, scheduleIterator)>
<!ATTLIST schedule className CDATA #REQUIRED>

<!--
  A task element defines a automatic printing task class.
  Usually, `org.F11.scada.server.autoprint.jasper.JasperAutoPrintTask'
  is specified.
-->
<!ELEMENT task (dataSource+)>
<!ATTLIST task className CDATA #REQUIRED>

<!--
  A dataSource element defines a datasource class.
  It is possible to set property to a class.
-->
<!ELEMENT dataSource (property*, exportor+)>
<!ATTLIST dataSource className CDATA #REQUIRED>

<!--
  An exportor element defines a data conversion class.
  A data conversion class can set up more than one.
  It is possible to set property to a class.
-->
<!ELEMENT exportor (property*)>
<!ATTLIST exportor className CDATA #REQUIRED>

<!--
  A scheduleIterator element defines the class which computes 
  the interval which performs a task.
  It is possible to set property to a class.
-->
<!ELEMENT scheduleIterator (property*)>
<!ATTLIST scheduleIterator className CDATA #REQUIRED>

<!--
  A property element sets up the property.
-->
<!ELEMENT property (#PCDATA)>
<!ATTLIST property name CDATA #REQUIRED
                   value CDATA #REQUIRED>

=== deckeeee/F-11/f-11-2.1.17/testResources/resources/task/task.xml
<?xml version="1.0" encoding="Shift_JIS" ?>

<!DOCTYPE tasks PUBLIC
          "-//Project F-11//DTD F-11 Task Configuration 1.0//JP"
          "http://f-11.sourceforge.jp/dtds/tasks_1_0.dtd">

<tasks>
	<schedule className="org.F11.scada.scheduling.Schedule">
		<task className="org.F11.scada.server.autoprint.jasper.JasperAutoPrintTask">
			<dataSource className="org.F11.scada.server.autoprint.jasper.data.DailyPrintDataSource">
				<property name="dataSourceSql" value="SELECT * FROM log_table_hour" />
				<property name="designPath" value="src/org/F11/scada/server/autoprint/jasper/data/design.xml" />
				<exportor className="org.F11.scada.server.autoprint.jasper.exportor.PdfExportor">
					<property name="out" value="c:/temp/daily%yyyyMMdd%.pdf" />
				</exportor>
			</dataSource>
		</task>
		<scheduleIterator className="org.F11.scada.server.autoprint.jasper.iterator.DailyIteratorJDBCWrapper">
			<property name="propertyTable" value="autoprint_property_table" />
			<property name="taskName" value="daily" />
		</scheduleIterator>
	</schedule>

	<schedule className="org.F11.scada.scheduling.Schedule">
		<task className="org.F11.scada.server.autoprint.jasper.JasperAutoPrintTask">
			<dataSource className="org.F11.scada.server.autoprint.jasper.data.MonthlyPrintDataSource">
				<property name="dataSourceSql" value="SELECT * FROM log_table_daily" />
				<property name="designPath" value="src/org/F11/scada/server/autoprint/jasper/data/design2.xml" />
				<exportor className="org.F11.scada.server.autoprint.jasper.exportor.PdfExportor">
					<property name="out" value="c:/temp/monthly%yyyyMM%.pdf" />
				</exportor>
			</dataSource>
		</task>
		<scheduleIterator className="org.F11.scada.server.autoprint.jasper.iterator.MonthlyIteratorJDBCWrapper">
			<property name="propertyTable" value="autoprint_property_table" />
			<property name="taskName" value="month" />
		</scheduleIterator>
	</schedule>
</tasks>
