=== deckeeee/F-11/f-11-2.1.33/src/resources/textoutput10.dtd
<?xml version="1.0" encoding="Windows-31J"?>
<!--
<!DOCTYPE textout PUBLIC "-//F-11 2.0//DTD F11 Textout Configuration//EN"
	"http://f-11.sourceforge.jp/dtds/textoutput10.dtd">
-->
<!ELEMENT textout (property+)>
<!ELEMENT property (#PCDATA)>
<!ATTLIST property name CDATA #REQUIRED
                   value CDATA #REQUIRED>

=== deckeeee/F-11/f-11.2.1.31/resources/TextOutput.xml
<?xml version="1.0" encoding="Windows-31J"?>
<!DOCTYPE textout PUBLIC "-//F-11 2.0//DTD F11 Textout Configuration//EN"
	"http://f-11.sourceforge.jp/dtds/textoutput10.dtd">

<textout>
	<property name="text" value="{&quot;power_demand&quot;:&quot;" />
	<property name="data" value="P1_D_500_BcdSingle" />
	<property name="text" value="&quot;,&quot;capacity&quot;:&quot;" />
	<property name="data" value="P1_D_501_BcdSingle" />
	<property name="text" value="&quot;,&quot;value&quot;:&quot;" />
	<property name="data" value="P1_D_1900001_Digital" />
	<property name="text" value="&quot;}&#x0D;&#x0A;" />
</textout>

=== deckeeee/F-11/F-11/tags/2014-01-30/f-11.2.1.31/resources/demand_forecast.xml
<?xml version="1.0" encoding="Windows-31J"?>
<!DOCTYPE textout PUBLIC "-//F-11 2.0//DTD F11 Textout Configuration//EN"
	"http://f-11.sourceforge.jp/dtds/textoutput10.dtd">

<textout>
	<property name="text" value="{&quot;demand_forecast&quot;:&quot;" />
	<property name="data" value="P1_D_502_BcdSingle" />
	<property name="text" value="&quot;,&quot;peak_time&quot;:&quot;" />
	<property name="data" value="P1_D_503_BcdSingle" />
	<property name="text" value="Žž‘ä&quot;,&quot;last_update&quot;:&quot;" />
	<property name="data" value="P1_D_504_BcdSingle" />
	<property name="text" value="&quot;}&#x0D;&#x0A;" />
</textout>
