=== deckeeee/F-11/f-11.2.1.30/src/resources/command20.dtd
<?xml version="1.0" encoding="Windows-31J"?>
<!--
<!DOCTYPE command-provider PUBLIC "-//F-11 2.0//DTD F11 Command Configuration//EN" 
	"http://f-11.sourceforge.jp/dtds/command20.dtd">
-->
<!ELEMENT command-provider (command | expression)*>
<!ELEMENT command (class+)>
<!ELEMENT expression (class+)>
<!ATTLIST command provider CDATA #REQUIRED
                  holder CDATA #REQUIRED>
<!ATTLIST expression value CDATA #REQUIRED
                  enableInitialMode CDATA #IMPLIED>
<!ELEMENT class (property*)>
<!ATTLIST class className CDATA #REQUIRED>
<!ELEMENT property (#PCDATA)>
<!ATTLIST property name CDATA #REQUIRED
                   value CDATA #REQUIRED>

=== deckeeee/F-11/F-11/tags/2016-01-19/f-11-2.1.32/2014-01-20/f-11.2.1.30/trunk/src/org/F11/scada/server/command/command.xml
<?xml version="1.0" encoding="Shift_JIS"?>
<!DOCTYPE command-provider PUBLIC "-//F-11 2.0//DTD F11 Command Configuration//EN" 
	"http://f-11.sourceforge.jp/dtds/command20.dtd">

<!--
	コマンドプロバイダ定義
-->

<command-provider>
	<command provider="P1" holder="D_1900000_Digital">
		<class className="org.F11.scada.server.command.FileWriteCommand">
			<property name="path" value="c:/temp/D1900000.txt" />
		</class>
	</command>

	<command provider="P1" holder="D_1900001_Digital">
		<class className="org.F11.scada.server.command.TestCommandClass">
			<property name="key" value="value" />
			<property name="name" value="name" />
			<property name="none" value="none" />
		</class>
		<class className="org.F11.scada.server.command.TestCommandClass">
			<property name="key" value="value2" />
			<property name="name" value="name2" />
			<property name="none" value="none2" />
		</class>
	</command>

	<expression value="P1_D_1900003_Digital || P1_D_1900004_Digital">
		<class className="org.F11.scada.server.command.WriteTermCommand">
			<property name="provider" value="P1"/>
			<property name="holder" value="D_500_BcdSingle"/>
			<property name="value" value="50"/>
		</class>
	</expression>
</command-provider>

=== deckeeee/F-11/f-11-2.1.11/resources/command.xml
<?xml version="1.0" encoding="Shift_JIS"?>
<!DOCTYPE command-provider PUBLIC "-//F-11 2.0//DTD F11 Command Configuration//EN" 
	"http://f-11.sourceforge.jp/dtds/command20.dtd">

<!--
	コマンドプロバイダ定義
-->

<!-- 実行定義　この部分を編集下さい-->
<command-provider>
	<command provider="P1" holder="D_1900000_Digital">
		<class className="org.F11.scada.server.command.FileWriteCommand">
			<property name="path" value="c:/temp/D1900000.txt" />
			<property name="errorRetryCount" value="1000" />
			<property name="errorRetryTime" value="100" />
		</class>
		<class className="org.F11.scada.server.command.FileWriteCommand">
			<property name="path" value="c:/temp/D1900000_1.txt" />
			<property name="errorRetryCount" value="1000" />
			<property name="errorRetryTime" value="100" />
		</class>
	</command>
	<command provider="P1" holder="D_1900001_Digital">
		<class className="org.F11.scada.server.command.FileExecuteCommand">
			<property name="path" value="notepad" />
		</class>
	</command>
	<command provider="P1" holder="D_1900002_Digital">
		<class className="org.F11.scada.server.command.NippoPrintCommand">
			<property name="outname" value="C:/temp/autoprint/ListOut.csv"/>
			<property name="header1" value="1" />
			<property name="header2" value="C:\temp\autoprint\tyohyo.XLS" />
			<property name="header3" value="1" />
			<property name="provider" value="P1"/>
			<property name="holder" value="D_601_BcdSingle"/>
			<property name="header5" value="0" />
			<property name="csv_dir" value="C:/temp/csv/" />
			<property name="csv_head" value="log_table_daily_" />
			<property name="csv_mid" value="yyyyMMDD" />
			<property name="csv_foot" value=".csv" />
			<property name="path" value="C:/Program Files/Microsoft Office/Office10/excel.exe" />
			<property name="param1" value="C:/temp/autoprint/PRINT.XLA" />
			<property name="param2" value="/e" />
		</class>
	</command>
	<command provider="P1" holder="D_1900003_Digital">
		<class className="org.F11.scada.server.command.GeppoPrintCommand">
			<property name="outname" value="C:/temp/autoprint/ListOut.csv"/>
			<property name="header1" value="1" />
			<property name="header2" value="C:\temp\autoprint\tyohyo.XLS" />
			<property name="header3" value="2" />
			<property name="provider" value="P1"/>
			<property name="holder" value="D_602_BcdSingle"/>
			<property name="header5" value="0" />
			<property name="csv_dir" value="C:/temp/csv/" />
			<property name="csv_head" value="log_table_monthly_" />
			<property name="csv_mid" value="yyyyMM" />
			<property name="csv_foot" value=".csv" />
			<property name="path" value="C:/Program Files/Microsoft Office/Office10/excel.exe" />
			<property name="param1" value="C:/temp/autoprint/PRINT.XLA" />
			<property name="param2" value="/e" />
		</class>
	</command>
	<expression value="P1_D_500_BcdSingle &gt; P1_D_501_BcdSingle">
		<class className="org.F11.scada.server.command.WriteTermCommand">
			<property name="provider" value="P1"/>
			<property name="holder" value="D_1900100_Digital"/>
			<property name="value" value="true"/>
		</class>
	</expression>
	<expression value="(P1_D_1900000_Digital || P1_D_1900001_Digital) &amp;&amp; (P1_D_500_BcdSingle &gt; P1_D_501_BcdSingle)">
		<class className="org.F11.scada.server.command.WriteTermCommand">
			<property name="provider" value="P1"/>
			<property name="holder" value="D_502_BcdSingle"/>
			<property name="value" value="50"/>
		</class>
	</expression>
</command-provider>
