=== deckeeee/F-11/f-11-2.1.25RC10/src/resources/tree10.dtd
<?xml version="1.0" encoding="Windows-31J"?>
<!--
<!DOCTYPE tree PUBLIC "-//F-11 2.0//DTD F11 Tree Configuration//EN" 
	"http://f-11.sourceforge.jp/dtds/tree10.dtd">
-->
<!ELEMENT tree (root)>
<!ATTLIST tree initpage CDATA #REQUIRED>
<!ELEMENT root (node*)>
<!ATTLIST root name CDATA #REQUIRED>
<!ELEMENT node (node*)>
<!ATTLIST node name CDATA #REQUIRED>
<!ATTLIST node page CDATA #IMPLIED>

=== deckeeee/F-11/F-11/tags/2011-08-16/f-11-2.1.22/treedefine/tree_user2.xml
<?xml version="1.0" encoding="WINDOWS-31J"?>
<!DOCTYPE tree PUBLIC "-//F-11 2.0//DTD F11 Tree Configuration//EN" "http://f-11.sourceforge.jp/dtds/tree10.dtd">

<tree initpage="状態一覧表">
	<root name="WifeProject_user2">
		<node name="スケジュール">
			<node name="カレンダー" page="カレンダー"/>
			<node name="スケジュール TABLE" page="スケジュール TABLE"/>
			<node name="スケジュール BAR" page="schedule02"/>
			<node name="スケジュール BAR2" page="schedule01"/>
			<node name="スケジュール BAR3" page="スケジュール BAR3"/>
		</node>
		<node name="グラフ">
			<node name="トレンドグラフ" page="TRND0001"/>
			<node name="日報バーグラフ" page="日報バーグラフ"/>
			<node name="月報バーグラフ" page="月報バーグラフ"/>
		</node>
		<node name="ツリーテスト">
			<node name="ツリー２">
				<node name="ツリー１平面図" page="空調平面図"/>
				<node name="ツリー１状態" page="状態一覧表"/>
				<node name="ツリー１計測" page="計測一覧表"/>
				<node name="積算テスト" page="UNTN0001"/>
			</node>
		</node>
	</root>
</tree>

=== deckeeee/F-11/F-11/tags/2016-01-19/f-11-2.1.32/2014-01-20/f-11.2.1.30/treedefine/tree.xml
<?xml version="1.0" encoding="WINDOWS-31J"?>
<!DOCTYPE tree PUBLIC "-//F-11 2.0//DTD F11 Tree Configuration//EN" 
	"http://f-11.sourceforge.jp/dtds/tree10.dtd">

<tree initpage="deeps">
	<root name="Wifeproject_def">
		<node name="重なり" page="deeps"/>
		<node name="一覧表">
			<node name="状態一覧表" page="状態一覧表"/>
			<node name="計測一覧表" page="計測一覧表"/>
		</node>
		<node name="平面図">
			<node name="空調平面図" page="空調平面図"/>
			<node name="スケルトン" page="スケルトン"/>
		</node>
		<node name="スケジュール">
			<node name="カレンダー" page="カレンダー"/>
			<node name="スケジュール TABLE" page="スケジュール TABLE"/>
			<node name="スケジュール TABLE" page="schetable2"/>
			<node name="スケジュール BAR" page="schedule02"/>
			<node name="スケジュール BAR2" page="schedule01"/>
			<node name="スケジュール BAR3" page="スケジュール BAR3"/>
		</node>
		<node name="グラフ">
			<node name="トレンドグラフ" page="TRND0001"/>
			<node name="トレンドグラフ" page="TRND0003"/>
			<node name="トレンドグラフ" page="TRND0004"/>
			<node name="トレンドグラフ" page="TRND0005"/>
			<node name="日報バーグラフ" page="日報バーグラフ"/>
			<node name="月報バーグラフ" page="月報バーグラフ"/>
			<node name="年報バーグラフ" page="nenpo"/>
			<node name="グラフシンボル" page="graphview"/>
			<node name="バーグラフ" page="バーグラフ"/>
		</node>
		<node name="デマンド" page="デマンド監視"/>
		<node name="ツリーテスト">
			<node name="ツリー１">
				<node name="空調平面図" page="空調平面図"/>
				<node name="状態一覧表" page="状態一覧表"/>
				<node name="計測一覧表" page="計測一覧表"/>
				<node name="空調平面図2" page="空調平面図2"/>
			</node>
			<node name="ツリー２">
				<node name="ツリー１平面図" page="空調平面図"/>
				<node name="ツリー１状態" page="状態一覧表"/>
				<node name="ツリー１計測" page="計測一覧表"/>
				<node name="積算テスト" page="UNTN0001"/>
				<node name="操作ログ検索" page="opelog"/>
			</node>
		</node>
	</root>
</tree>
